name  'puppetlabs-osxbuilder'
version '0.0.1'
summary 'OSX package builder'
description 'Module to set pu an osx builder'
dependency  'ploperations/git', '>= 0.0.2'
project_page  'https://github.com/puppetlabs/puppetlabs-osxbuilder.git'
license 'Apache 2.0'
author  'puppetlabs'
source  'git@github.com:puppetlabs/puppetlabs-osxbuilder.git'
